### ISSUE TITLE
lib文件夹下有一些代码有问题

### ISSUE THREAD

**Issue by Gaubee** [DoubleSpout/ccap#15]
我自己因为使用KOA框架不得不自己另外开了一个分支。因为nodejs v0.11.*的插件开发有所出入。所以不是很方便给你推送代码。
代码库在：http://git.oschina.net/Gaubee/uns-ccap/tree/non-standard/lib
主要的改动在js方面，最大的问题是我看了你的CAP函数后发现并不能支持所谓的：
```js
CAP(W,H,O);
```
这样的传参。
具体改进在：http://git.oschina.net/Gaubee/uns-ccap/commit/8efd8bc53bfa8afd69c4ebc2b94d5720bb8d43d6

您可以自行舍取。

**Comment by DoubleSpout** [comment]
这块很难调整，还有算法啥的，没时间去弄了，谢谢你的代码
