### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by jerryxht** [DoubleSpout/ccap#26]
centos6.5 
node v0.10.35
python2.6.6时安装如下错误信息
======================================================================
npm http GET https://registry.npmjs.org/ccap
npm http 304 https://registry.npmjs.org/ccap

> ccap@0.5.2 preinstall /mnt2/tamenshuowangzhanmingzhichanglehekejiubuhaocaizheshizhendeme/group/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
npm http GET https://registry.npmjs.org/node-schedule/0.1.13
npm http 304 https://registry.npmjs.org/node-schedule/0.1.13

> ccap@0.5.2 install /mnt2/tamenshuowangzhanmingzhichanglehekejiubuhaocaizheshizhendeme/group/node_modules/ccap
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/bin/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 462, in main
    options.circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 100, in Load
    depth, generator_input_info, check, circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 2255, in Load
    depth, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 217, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt2/tamenshuowangzhanmingzhichanglehekejiubuhaocaizheshizhendeme/group/node_modules/ccap
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

升级到python2.7.8然后安装如下错误信息
======================================================================
npm http GET https://registry.npmjs.org/ccap
npm http 304 https://registry.npmjs.org/ccap

> ccap@0.5.2 preinstall /mnt2/tamenshuowangzhanmingzhichanglehekejiubuhaocaizheshizhendeme/group/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
npm http GET https://registry.npmjs.org/node-schedule/0.1.13
npm http 304 https://registry.npmjs.org/node-schedule/0.1.13

> ccap@0.5.2 install /mnt2/tamenshuowangzhanmingzhichanglehekejiubuhaocaizheshizhendeme/group/node_modules/ccap
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/bin/gyp", line 15, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt2/tamenshuowangzhanmingzhichanglehekejiubuhaocaizheshizhendeme/group/node_modules/ccap
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by libook** [comment]
我使用[io.js](https://iojs.org/) v1.1.0, v8版本4.1.0.14，node-gyp版本1.0.2，编译日志如下：

-
> ccap@0.5.2 preinstall /home/libook/Documents/GitProjects/libook/matrix/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
|
> ccap@0.5.2 install /home/libook/Documents/GitProjects/libook/matrix/node_modules/ccap
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/libook/Documents/GitProjects/libook/matrix/node_modules/ccap/build'
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jaricom.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcapimin.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcapistd.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcarith.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jccoefct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jccolor.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcdctmgr.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jchuff.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcinit.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcmainct.o
../addon/jpeglib/jcmainct.c: 在函数‘start_pass_main’中:
../addon/jpeglib/jcmainct.c:71:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jcmainct.c: 在函数‘process_data_simple_main’中:
../addon/jpeglib/jcmainct.c:117:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jcmainct.c: 在函数‘jinit_c_main_controller’中:
../addon/jpeglib/jcmainct.c:247:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main;
               ^
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcmarker.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcmaster.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcomapi.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcparam.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcprepct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcsample.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jctrans.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdapimin.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdapistd.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdarith.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdatadst.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdatasrc.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdcoefct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdcolor.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jddctmgr.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdhuff.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdinput.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmainct.o
../addon/jpeglib/jdmainct.c: 在函数‘alloc_funny_pointers’中:
../addon/jpeglib/jdmainct.c:162:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘make_funny_pointers’中:
../addon/jpeglib/jdmainct.c:203:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘set_wraparound_pointers’中:
../addon/jpeglib/jdmainct.c:243:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘set_bottom_pointers’中:
../addon/jpeglib/jdmainct.c:272:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘start_pass_main’中:
../addon/jpeglib/jdmainct.c:309:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘process_data_simple_main’中:
../addon/jpeglib/jdmainct.c:349:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘process_data_context_main’中:
../addon/jpeglib/jdmainct.c:389:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘jinit_d_main_controller’中:
../addon/jpeglib/jdmainct.c:478:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main;
               ^
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmarker.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmaster.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmerge.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdpostct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdsample.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdtrans.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jerror.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jfdctflt.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jfdctfst.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jfdctint.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jidctflt.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jidctfst.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jidctint.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jquant1.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jquant2.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jutils.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jmemmgr.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jmemnobs.o
  CXX(target) Release/obj.target/hcaptha/addon/hcaptha.o
In file included from ../addon/hcaptha.cc:3:0:
../addon/cap.h:11:49: 错误：‘Arguments’不是命名空间‘v8’中的一个类型名
   static v8::Handle<v8::Value> create(const v8::Arguments& args);
                                                 ^
../addon/hcaptha.cc: 在函数‘void Init(v8::Handle<v8::Object>)’中:
../addon/hcaptha.cc:13:15: 错误：‘NewSymbol’不是‘v8::String’的成员
   target->Set(String::NewSymbol("create"),
               ^
../addon/hcaptha.cc:14:45: 错误：对‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’的调用没有匹配的函数
            FunctionTemplate::New(cap::create)->GetFunction());
                                             ^
../addon/hcaptha.cc:14:45: 附注：备选是：
In file included from /home/libook/.node-gyp/1.1.0/src/node.h:40:0,
                 from ../addon/hcaptha.cc:2:
/home/libook/.node-gyp/1.1.0/deps/v8/include/v8.h:3823:34: 附注：static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/libook/.node-gyp/1.1.0/deps/v8/include/v8.h:3823:34: 附注：  no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
hcaptha.target.mk:145: recipe for target 'Release/obj.target/hcaptha/addon/hcaptha.o' failed
make: *** [Release/obj.target/hcaptha/addon/hcaptha.o] Error 1
make: Leaving directory '/home/libook/Documents/GitProjects/libook/matrix/node_modules/ccap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Linux 3.18.5-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/libook/Documents/GitProjects/libook/matrix/node_modules/ccap
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.18.5-1-ARCH
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "ccap" "--save"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.5.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/libook/Documents/GitProjects/libook/matrix/npm-debug.log

**Comment by libook** [comment]
卸载io.js重装node解决

**Comment by DoubleSpout** [comment]
目前已经支持 nodejs 0.12.x 版本，也兼容老的 0.8.x - 0.10.x 安装方法见readme.md
