### ISSUE TITLE
OS X上由于每分钟更新缓存导致的IO错误

### ISSUE THREAD

**Issue by lizhuoli1126** [DoubleSpout/ccap#28]
操作系统:
OS X 10.0.2(14C109)
Node v0.10.33
ccap@0.5.2

错误日志:
    [CImg] *** CImgIOException *** cimg::fopen(): Failed to open file '~/xxx/node_modules/ccap/cap_img/captcha_126_1233_1426597209553_18.bmp' with mode 'wb'.
libc++abi.dylib: terminating with uncaught exception of type cimg_library::CImgIOException
Abort trap: 6

错误原因:
在自动更新缓存（默认1分钟）的时候，计时使用的是这样的方法
    		setTimeout(function(){
			timer.timer();
		}, timer.timeout)

这个计时是由Node实现的，基本无任何误差，和任何IO无关，现在先记住这点。
调用的_timer()方法会再次调用如下两行语句：this._get_count++;//记录timer调用次数 （这个我没发现在哪里有用，不知道功能）
this._create();
而_create()会调用选择的字符串生成方法（自定义或者默认），函数入口var CAP = function(args){...}在倒数第二行_create()之后，还有一条：
    this.is_first = false;

这个is_first在98行进行了判断，如果为真（第一次生成）就用readFileSync，反之（readFile），就是在这里出了问题。
本来选择同步读取是因为知道此时已经通过Cimg生成了图片并且缓存在本地，但是如果是通过定时器重置缓存的调用，对象的is_first还是false，所以，一定会用readFile进行异步读取，这样就会出现问题：假如采用这种同步读的时候，下一个请求又给了Cimg，Cimg需要进行写，由于是同步读加上同步写，就会出现IOException。

解决方法：
很简单，在_timer()里面，加上
    this.is_first = true
再次把is_first改回true，下次在_call_create()中就会采用readFileSync，既不影响已缓存文件异步读取效率，也解决了IO冲突。
在本人自己电脑上测试通过，已经发了pull request……真实情况请各位前辈看看（Node新手，大二菜鸟）

**Comment by DoubleSpout** [comment]
谢谢你的分析，这里确实可能存在问题，不过is_first不光是这边使用，所以我把hcap.js中，_all_create所有都通过同步读取文件了，这样也就没有你说的那个bug了，一会我提交新版本，麻烦你再帮我测试下，我这里没mac~

**Comment by DoubleSpout** [comment]
目前已经支持 nodejs 0.12.x 版本，也兼容老的 0.8.x - 0.10.x 安装方法见readme.md，另外你的bug也改掉了~非常感谢啊
