### ISSUE TITLE
windows and linux 永远编译出错啊。

### ISSUE THREAD

**Issue by oSpring** [DoubleSpout/ccap#34]
windows and linux 永远编译出错啊。

**Comment by DoubleSpout** [comment]
报什么错误？

**Comment by oSpring** [comment]
D:\sync\insurance\bin>npm install ccap
|
> ccap@0.6.0 preinstall D:\sync\insurance\node_modules\ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
|
> ccap@0.6.0 install D:\sync\insurance\node_modules\ccap
> node-gyp rebuild


D:\sync\insurance\node_modules\ccap>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100
') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools b
y selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [D:\sync\insurance\node_modules\ccap\build\hcaptha.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\sync\insurance\node_modules\ccap
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ccap"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccap@0.6.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sync\insurance\bin\npm-debug.log


报这个错误，然后专门用了虚拟机装了VS2010，有提示要下载 node 的 tar.gz 的包。

目前环境是 VS2015 update 4

**Comment by oSpring** [comment]
mac 下这个错误。
$ npm install ccap

npm WARN engine ccap@0.6.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.33","npm":"1.4.28"})

> ccap@0.6.0 preinstall /Users/yimity/sync/sync/insurance/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
-
> ccap@0.6.0 install /Users/yimity/sync/sync/insurance/node_modules/ccap
> node-gyp rebuild

  CXX(target) Release/obj.target/hcaptha/addon/hcaptha.o
In file included from ../addon/hcaptha.cc:2:
../addon/cap.h:11:28: error: unknown type name 'FunctionCallbackInfo'
  static void create(const FunctionCallbackInfo<Value>& args);
                           ^
../addon/cap.h:11:48: error: expected ')'
  static void create(const FunctionCallbackInfo<Value>& args);
                                               ^
../addon/cap.h:11:21: note: to match this '('
  static void create(const FunctionCallbackInfo<Value>& args);
                    ^
2 errors generated.
make: *** [Release/obj.target/hcaptha/addon/hcaptha.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yimity/sync/sync/insurance/node_modules/ccap
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! ccap@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.6.0 install script.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "ccap"
npm ERR! cwd /Users/yimity/sync/sync/insurance
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by DoubleSpout** [comment]
对于node.js 0.10.x版本，使用下面的命令安装吧：

    npm install ccap@0.5.3

**Comment by oSpring** [comment]
今天调整了下 Python 的目录，解决编译 node-canvas 的问题之后，编译这个，又成功了。windows 平台。
