### ISSUE TITLE
linux install ccap failed

### ISSUE THREAD

**Issue by CruiseDuan** [DoubleSpout/ccap#35]
--Python 2.4.3 (#1, Dec 10 2010, 17:24:35)
npm ERR! Linux 2.6.18-238.el5
npm ERR! argv "/usr/src/nodejs/bin/node" "/usr/src/nodejs/bin/npm" "install" "ccap"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR! 
npm ERR! If you need help, you may report this error at:

npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
228 error Linux 2.6.18-238.el5
229 error argv "/usr/src/nodejs/bin/node" "/usr/src/nodejs/bin/npm" "install" "ccap"
230 error node v0.12.6
231 error npm  v2.11.2
232 error code EAI_AGAIN
233 error errno EAI_AGAIN
234 error syscall getaddrinfo
235 error getaddrinfo EAI_AGAIN
236 error If you need help, you may report this error at:
236 error     <https://github.com/npm/npm/issues>
237 verbose exit [ 1, true ]
238 verbose unbuild node_modules/ccap
239 info preuninstall ccap@0.6.0
240 info uninstall ccap@0.6.0
241 verbose unbuild rmStuff ccap@0.6.0 from /usr/src/sunrise/node_modules
242 info postuninstall ccap@0.6.0
243 silly gentlyRm /usr/src/sunrise/node_modules/ccap is being purged from base /usr/src/sunrise
244 verbose gentlyRm don't care about contents; nuking /usr/src/sunrise/node_modules/ccap
245 silly vacuum-fs purging /usr/src/sunrise/node_modules/ccap
246 silly vacuum-fs quitting because other entries in /usr/src/sunrise/node_modules

**Comment by DoubleSpout** [comment]
python版本过低，请使用2.7.x

**Comment by CruiseDuan** [comment]
OK,谢谢



段玉飞
北京天融互联信息技术有限公司
地址：北京朝阳区建国门外大街甲6号中环世贸D座32层
手机：13146284683
邮箱：duanyufei@e-tianrong.com
 
From: spout
Date: 2015-08-17 16:57
To: DoubleSpout/ccap
CC: CuriesD
Subject: Re: [ccap] linux install ccap failed (#35)
python版本过低，请使用2.7.x
