### ISSUE TITLE
库内部大量使用同步方法导致性能较差

### ISSUE THREAD

**Issue by winsonwq** [DoubleSpout/ccap#37]
例子：

CAP 对象中的 _call_create 的写文件和读文件都是同步方法，并且在 _custom_create 或者 _default_create 方法中是默认循环 20 次调用。node 环境下这样的代码性能会非常差，尤其在多次创建 CAP 对象的情况下。

**Comment by DoubleSpout** [comment]
只有在刚启动初始化时会用同步的方法，生成验证码目前是在C++代码端同步写入文件，接下来会考虑用Libuv开启线程异步写文件
