### ISSUE TITLE
node.js v4.0.0 支持

### ISSUE THREAD

**Issue by jackhutu** [DoubleSpout/ccap#39]
希望能尽快支持node.js v4.0.0.

**Comment by wanming** [comment]
+100086，很急很关键！

**Comment by DoubleSpout** [comment]
我在node v4.1.1上安装了一次，没问题

**Comment by snadn** [comment]
@DoubleSpout 现在好像是在windows平台能正常安装，但在linux上会出错。

![image](https://cloud.githubusercontent.com/assets/1269858/10355368/9674c38a-6d9d-11e5-8061-1a9ff146ed30.png)

**Comment by DoubleSpout** [comment]
新版本已经修复了，4.1.2上测试通过，但是如果直接编译的话需要升级gcc版本，也可以直接下载代码包，把`release`文件夹下的内容拷贝出来，那是已经编译好的·.node·文件

**Comment by snadn** [comment]
@DoubleSpout 需要的gcc版本是多少呢？

**Comment by DoubleSpout** [comment]
Sorry，文件夹被`.gitignore`屏蔽了，我修改了下，提交上来了~
