### ISSUE TITLE
MAC下面无法安装使用

### ISSUE THREAD

**Issue by wavelynn** [DoubleSpout/ccap#43]
之前直接npm install ccap，编译不通过

后来升级了gcc为4.8.4也还是无法编译通过
> node-gyp rebuild

  CXX(target) Release/obj.target/hcaptha/addon/hcaptha.o
  CXX(target) Release/obj.target/hcaptha/addon/cap.o
../addon/cap.cc:81:44: warning: unused variable 'green' [-Wunused-variable]
  const unsigned char red[] = { 255,0,0 }, green[] = { 0,255,0 }, blue[] = { 0,0,255 };
                                           ^
../addon/cap.cc:81:67: warning: unused variable 'blue' [-Wunused-variable]
  const unsigned char red[] = { 255,0,0 }, green[] = { 0,255,0 }, blue[] = { 0,0,255 };
                                                                  ^
../addon/cap.cc:84:29: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
  for (unsigned int k = 0; k<count; ++k) {
                           ~^~~~~~
3 warnings generated.
  SOLINK_MODULE(target) Release/hcaptha.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/hcaptha.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ccap" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.6.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by cssgdhd** [comment]
同样的问题，本以为是gcc版本不太低，准备更新gcc，但是现在看来，并非如此

**Comment by DoubleSpout** [comment]
什么node.js版本

**Comment by maoanran** [comment]
brew install pkg-config
brew install cairo

**Comment by helloyokoy** [comment]
@maoanran  thanks ! it worked~
