### ISSUE TITLE
centos6.6 安装失败的原因

### ISSUE THREAD

**Issue by zhangda89** [DoubleSpout/ccap#44]
第一个原因是Python下版本的问题，请更换为Python2.7
第二个原因是gcc的版本问题，请更新gcc的版本为gcc 4.8+

第二个问题打开可以参考这里：
http://www.gowhich.com/blog/722
我已经整理好了。
第一个问题的话，有人说，比如我，不想更改本地的python，那么我推荐一个办法是，使用virtualenv，因为这个工具可以指定你安装的python的版本，就不需要替换本地的，只需要指定一下python版本的位置就好了，如：virtualenv --python=/path/to/bin/python2.7 env,然后 source ./env/bin/activate 这样python的版本就是2.7的啦，当然使用3的话也可以，就是ccap不支持而已，好了，我整理了一下，希望对大家有用，这个ccap还是不错的。

**Comment by DoubleSpout** [comment]
python3不是ccap不支持，是node-gyp不支持。
