### ISSUE TITLE
请求支持最新的 Node.JS 版本（v5.6.0）

### ISSUE THREAD

**Issue by XuJinNet** [DoubleSpout/ccap#53]
ccap 确实很好用，希望能够支持最新的 Node.JS 版本（5.6.0），Node.JS 5.1.1 下可以使用，只是 install 的时候有 WARN；在 Node.JS 5.6.0 下 install 时无法编译通过（操作系统：Windows 10 64bit）。

**Comment by DoubleSpout** [comment]
新版本支持了 6.2.0，5.x版本是开发版，不做支持了，会支持稳定版本的node
