### ISSUE TITLE
win7 64 err

### ISSUE THREAD

**Issue by NateZh** [DoubleSpout/ccap#54]
D:\code\WebStormProjects\golden_evaluating\node_modules\ccap>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
"" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35-32\python.EXE" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:475:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\code\WebStormProjects\golden_evaluating\node_modules\ccap
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
graceful-readlink@1.0.1 node_modules\node-xlsx\node_modules\xlsx\node_modules\commander\node_modules\graceful-readlink -> node_modules\graceful-readlink
process-nextick-args@1.0.6 node_modules\node-xlsx\node_modules\xlsx\node_modules\process-nextick-args -> node_modules\process-nextick-args
typedarray@0.0.6 node_modules\node-xlsx\node_modules\xlsx\node_modules\codepage\node_modules\concat-stream\node_modules\typedarray -> node_modules\typedarray
util-deprecate@1.0.2 node_modules\node-xlsx\node_modules\xlsx\node_modules\util-deprecate -> node_modules\util-deprecate
readable-stream@2.0.5 node_modules\node-xlsx\node_modules\xlsx\node_modules\codepage\node_modules\concat-stream\node_modules\readable-stream -> node_modules\node-xlsx\node_modules\readable-stream
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ccap"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccap@0.6.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ccap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\code\WebStormProjects\golden_evaluating\npm-debug.log

**Comment by NateZh** [comment]
node -v
v5.7.0

**Comment by NateZh** [comment]
python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32

**Comment by huqiliang** [comment]
win7 64位我也报错 
报错信息如下：

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api
and lightweight.

starting compile ccap! good luck!
-
> ccap@0.6.4 install D:\test\node_modules\ccap
> node-gyp rebuild


D:\test\node_modules\ccap>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (rebuild)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  hcaptha.cc
  cap.cc
..\addon\cap.cc : warning C4819: The file contains a character that cannot be r
epresented in the current code page (936). Save the file in Unicode format to p
revent data loss [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\addon\hcaptha.cc) [D:\test\node_modules\ccap\build\hcaptha.vc
xproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxpro
j]
..\addon\cap.cc(84): warning C4018: '<' : signed/unsigned mismatch [D:\test\nod
e_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(17021): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(17019) : while compili
  ng class template member function 'cimg_library::CImg<char> cimg_library::CIm
  g<char>::string(const char *const ,const bool)'
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(41011) : see reference
   to function template instantiation 'cimg_library::CImg<char> cimg_library::C
  Img<char>::string(const char *const ,const bool)' being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(13680) : see reference
   to class template instantiation 'cimg_library::CImg<char>' being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(15764) : see reference
   to class template instantiation 'cimg_library::CImg<float>::_cimg_math_parse
  r' being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(15762) : while compili
  ng class template member function 'double cimg_library::CImg<float>::eval(con
  st char *const ,const double,const double,const double,const double) const'
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(46145) : see reference
   to function template instantiation 'double cimg_library::CImg<float>::eval(c
  onst char *const ,const double,const double,const double,const double) const'
   being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(46144) : see reference
   to class template instantiation 'cimg_library::CImg<float>' being compiled
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18837): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18831) : while compili
  ng class template member function 'cimg_library::CImg<char> &cimg_library::CI
  mg<char>::_system_strescape(void)'
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(41011) : see reference
   to function template instantiation 'cimg_library::CImg<char> &cimg_library::
  CImg<char>::_system_strescape(void)' being compiled
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18837): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18838): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18838): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18839): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18839): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18840): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18840): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18841): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18841): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18843): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [D:\test\node_module
s\ccap\build\hcaptha.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\node_modules\ccap
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "ccap"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccap@0.6.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\npm-debug.log

D:\test>npm install ccap /m
npm ERR! addLocal Could not install D:\m
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "ccap" "/m"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path D:\m
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'D:\m'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\npm-debug.log

D:\test>npm install ccap

> ccap@0.6.4 preinstall D:\test\node_modules\ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api
and lightweight.

starting compile ccap! good luck!
/
> ccap@0.6.4 install D:\test\node_modules\ccap
> node-gyp rebuild


D:\test\node_modules\ccap>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (rebuild)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  hcaptha.cc
  cap.cc
..\addon\cap.cc : warning C4819: The file contains a character that cannot be r
epresented in the current code page (936). Save the file in Unicode format to p
revent data loss [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\addon\hcaptha.cc) [D:\test\node_modules\ccap\build\hcaptha.vc
xproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxpro
j]
..\addon\cap.cc(84): warning C4018: '<' : signed/unsigned mismatch [D:\test\nod
e_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(17021): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(17019) : while compili
  ng class template member function 'cimg_library::CImg<char> cimg_library::CIm
  g<char>::string(const char *const ,const bool)'
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(41011) : see reference
   to function template instantiation 'cimg_library::CImg<char> cimg_library::C
  Img<char>::string(const char *const ,const bool)' being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(13680) : see reference
   to class template instantiation 'cimg_library::CImg<char>' being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(15764) : see reference
   to class template instantiation 'cimg_library::CImg<float>::_cimg_math_parse
  r' being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(15762) : while compili
  ng class template member function 'double cimg_library::CImg<float>::eval(con
  st char *const ,const double,const double,const double,const double) const'
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(46145) : see reference
   to function template instantiation 'double cimg_library::CImg<float>::eval(c
  onst char *const ,const double,const double,const double,const double) const'
   being compiled
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(46144) : see reference
   to class template instantiation 'cimg_library::CImg<float>' being compiled
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18837): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18831) : while compili
  ng class template member function 'cimg_library::CImg<char> &cimg_library::CI
  mg<char>::_system_strescape(void)'
          d:\test\node_modules\ccap\addon\jpeglib/CImg.h(41011) : see reference
   to function template instantiation 'cimg_library::CImg<char> &cimg_library::
  CImg<char>::_system_strescape(void)' being compiled
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18837): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18838): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18838): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18839): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18839): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18840): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18840): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18841): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18841): warning C4267: 'argument
' : conversion from 'size_t' to 'const unsigned int', possible loss of data (..
\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
d:\test\node_modules\ccap\addon\jpeglib/CImg.h(18843): warning C4244: 'argument
' : conversion from '__int64' to 'const unsigned int', possible loss of data (.
.\addon\cap.cc) [D:\test\node_modules\ccap\build\hcaptha.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [D:\test\node_module
s\ccap\build\hcaptha.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\node_modules\ccap
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "ccap"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ccap@0.6.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\npm-debug.log

版本信息如下：
node -v
v0.12.2

python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by DoubleSpout** [comment]
python 2.7 upgrade your `nodejs` version and `node-gyp` version, using `cnpm`~
