### ISSUE TITLE
`cap_img`文件夹下自动出现的图片是什么呢？

### ISSUE THREAD

**Issue by brickyang** [DoubleSpout/ccap#55]
刚装上后第二天发现`cap_img`文件夹下几千张自动生成的`bmp`图片，看了下似乎是每调用一次`.get()`就生成20张图，这是什么情况。。。

**Comment by satrong** [comment]
作者好像加了任务计划，凌晨两点清空一次。
https://github.com/DoubleSpout/ccap/blob/master/lib/hcap.js#L55

**Comment by brickyang** [comment]
@satrong 谢谢。我自己也做了一个定时任务每天清空。我回头看看
