### ISSUE TITLE
_cache_num不能自定义？

### ISSUE THREAD

**Issue by lemonbug** [DoubleSpout/ccap#58]
我只想生成1个验证码，可是你默认值是20？！还不能接受自定义？。。。起码加个接受参数设定吧。。

**Comment by satrong** [comment]
看了代码，它是每1分钟生成20张图片，然后在这1分钟之内在这刚生成的20张图片中随机选一个出来作为验证码，所以你不断的刷新验证码会看到有重复的验证码出现。所以如果那个参数设置为1就会出现验证码一直不变。大致看了代码应该就是这样子的

**Comment by DoubleSpout** [comment]
是这样的，这个值可以改的吧
