### ISSUE TITLE
node-gyp rebuild Error

### ISSUE THREAD

**Issue by lishoulong** [DoubleSpout/ccap#60]
Hi,the following informations,the platform is windows8.
node-gyp:  v3.3.1
python:  v2.7
node:v5.10.0,
My path of python is "D:\software\python",and I add it to the environment variable,in the console, tab python -v ,the version information shows. But when I install ccap it just show "Error: Can`t find Python executable "C:\Python27\python.exe",you can set the PYTHON env variable".
I tried some ways as search the "C:\Python27\python.exe" in the regedit,but I can`t find the relevant information.

**Comment by satrong** [comment]
Windows node 6.2.0 似乎不兼容，Linux可以

**Comment by satrong** [comment]
win10 + node 6.2.0 编译成功了，原来是我的vs没有安装c++组件。
@lishoulong , set the PYTHON env variable

**Comment by DoubleSpout** [comment]
今天我来修复下ccap，支持下node最新版本
