### ISSUE TITLE
验证码重复问题

### ISSUE THREAD

**Issue by satrong** [DoubleSpout/ccap#63]
@DoubleSpout 看你好像好久没上github了，端午节才有空啊。

我现在有一个站在用ccap，但我发现在20张图片里面1分钟内随机选择会存在重复的验证码，我现在改成直接调用你的生成图片的库的接口，每一个请求就生成一个验证码图片，然后读取验证码流返回给客户端同时删除生成的图片。但这样也会存在一个问题：很好吃性能。

我在想你之所以做成20张里面随机选择是不是为了减少电脑性能的消耗，还是其他什么问题？

**Comment by DoubleSpout** [comment]
就是为了减少性能的消耗，才20张随机获取一张的，如果你觉得随机度不够，可以修改20为50，100这样子

**Comment by satrong** [comment]
@DoubleSpout 这样还是有几率重复的，而且如果一下子生成100张，在那生成的过程中会不会突然很耗性能

**Comment by DoubleSpout** [comment]
会耗一些性能
