### ISSUE TITLE
从0.6.4升级到0.6.5出现no such file or directory错误，无法生成验证码

### ISSUE THREAD

**Issue by Shawyeok** [DoubleSpout/ccap#65]
原样的代码在0.6.4下正常工作，某次上线重新`npm install`之后发现无法生成验证码，错误日志如下：
```
x'x'x-app-0 (out): 2016-06-12 21:53 +08:00: { [Error: ENOENT: no such file or directory, mkdir '/src/node_modules/ccap/cap_img/9']
xxx-app-0 (out):   errno: -2,
xxx-app-0 (out):   code: 'ENOENT',
xxx-app-0 (out):   syscall: 'mkdir',
xxx-app-0 (out):   path: '/src/node_modules/ccap/cap_img/9' }
```

排查之后发现ccap版本前后有变化，安装了0.6.5版本，版本回退之后恢复正常

**Comment by maoanran** [comment]
@Shawyeok You can mkdir '/node_modules/ccap/cap_img' to figure out this issue.
I pushed a commit to let ccap works with cluster mode in 0.6.5, and there is a little bug, the cap_img dir is not packged in. Sorry for this!

**Comment by Shawyeok** [comment]
@maoanran It works after created `cap_img` directory. Maybe you should publish again to fix this problem.

**Comment by maoanran** [comment]
@Shawyeok  Yes, reladted pr https://github.com/DoubleSpout/ccap/pull/64.

**Comment by DoubleSpout** [comment]
再升级到0.6.9
