### ISSUE TITLE
升级到0.6.5后无法生成验证码

### ISSUE THREAD

**Issue by chenjihu** [DoubleSpout/ccap#66]
0.6.4版本的临时图片会在cap_img文件夹下，0.6.5变成了在cap_img/0目录下，其中有个fs.mkdirSync方法就报错了，无法创建多级目录。请修复。

**Comment by maoanran** [comment]
See https://github.com/DoubleSpout/ccap/issues/65

**Comment by DoubleSpout** [comment]
升级到0.6.7
