### ISSUE TITLE
这两天安装出现的问题！

### ISSUE THREAD

**Issue by kusion** [DoubleSpout/ccap#69]
之前，一直在安装ccap模块时，都是在:
centos 6.5
python 2.7.x 
node 0.12.x 
gcc 4.4.7(centos默认)
在这些环境下，安装都正常的。

---------------------------------------------------------------------------------
最近，把node换到了4.4.5之后，就安装不上了，编译到一半，就出错了：
/root/.node-gyp/4.4.5/include/node/v8.h:852: error: expected unqualified-id before 'using'
/root/.node-gyp/4.4.5/include/node/v8.h:1089: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.4.5/include/node/v8.h:1095: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.4.5/include/node/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
/root/.node-gyp/4.4.5/include/node/v8.h:3205: error: 'nullptr' was not declared in this scope
/root/.node-gyp/4.4.5/include/node/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
/root/.node-gyp/4.4.5/include/node/v8.h:7164: error: 'nullptr' was not declared in this scope
make: *** [Release/obj.target/hcaptha/addon/hcaptha.o] Error 1
make: Leaving directory `/opt/node-test/node_modules/ccap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-358.6.1.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v4.4.5/bin/node" "/root/.nvm/versions/node/v4.4.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node-test/node_modules/ccap
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-358.6.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.4.5/bin/node" "/root/.nvm/versions/node/v4.4.5/bin/npm" "install" "ccap"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.6.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ccap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

留意到，安装介绍提到“on linux need gcc v4.8+”，曾尝试将centos 6.5默认的4.4.7升级到4.8+，但过程太漫长了，并且也没升级成功！郁闷之中，无奈只能放弃升级gcc了，将node切换到0.12.x之后，再安装ccap，编译通过。
故，不知道node 4.4.5版本如何才能正常安装ccap模块，难道真的要升级gcc吗？

**Comment by DoubleSpout** [comment]
应该要连带升级一下node-gyp吧，你试试升级 node-gyp 再编译
