### ISSUE TITLE
verbose console.error issue

### ISSUE THREAD

**Issue by hyss777** [DoubleSpout/ccap#70]
my ccap version is 0.6.5

in file
lib/dir.js
line about 55

There is a verbose console.error(e) which does not check e!==null
![wrong_console_error](https://cloud.githubusercontent.com/assets/3783111/16289056/9a020b40-3924-11e6-8bad-a9c8584ffcb0.png)

you can see my screan shot

this makes ccap console.error a lot of "null", after you require('ccap') when the server have generated any captcha when the last time it was opened.

**Comment by DoubleSpout** [comment]
thx i have fix the bug in version 0.6.7
