### ISSUE TITLE
Failed at the ccap@0.6.4 preinstall script 'node make.js'.

### ISSUE THREAD

**Issue by wshm7366298** [DoubleSpout/ccap#72]
npm ERR! Linux 2.6.32-358.el6.x86_64
npm ERR! argv "/usr/local/node-v4.4.7-linux-x64/bin/node" "/usr/local/bin/npm" "bugs" "ccap"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code 3

npm ERR! Command failed: xdg-open https://github.com/DoubleSpout/ccap/issues
npm ERR! /usr/bin/xdg-open: line 402: htmlview: command not found
npm ERR! /usr/bin/xdg-open: line 402: firefox: command not found
npm ERR! /usr/bin/xdg-open: line 402: mozilla: command not found
npm ERR! /usr/bin/xdg-open: line 402: netscape: command not found
npm ERR! /usr/bin/xdg-open: line 402: links: command not found
npm ERR! /usr/bin/xdg-open: line 402: lynx: command not found
npm ERR! xdg-open: no method available for opening 'https://github.com/DoubleSpout/ccap/issues'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by DoubleSpout** [comment]
update to 0.6.9
