### ISSUE TITLE
error after upgrade to v6.3.1

### ISSUE THREAD

**Issue by wenjoy** [DoubleSpout/ccap#78]
i used this module ,when try to run my application,I got an error:
**relocating /var/www/wifi_nodejs/Wifi-HTTP-Server/node_modules/ccap/build/Release/hcaptha.node: __fprintf_chk: symbol not found**

my node is v.6.3.1,on ubuntu 14.04.1.
Did any know what does it means?

**Comment by DoubleSpout** [comment]
just run `npm install ccap`,you can not download it directly.
