### ISSUE TITLE
centos 6.8 python2.7.9 gcc4.8.1 无法编译ccap

### ISSUE THREAD

**Issue by nws123045088** [DoubleSpout/ccap#79]
../addon/jpeglib/jdmainct.c: In function ‘process_data_context_main’:
../addon/jpeglib/jdmainct.c:389:15: warning: ‘main’ is usually a function [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: In function ‘jinit_d_main_controller’:
../addon/jpeglib/jdmainct.c:478:15: warning: ‘main’ is usually a function [-Wmain]
   my_main_ptr main;
               ^
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmarker.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmaster.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmerge.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdpostct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdsample.o
/tmp/cc1ehp39.s: Assembler messages:
/tmp/cc1ehp39.s:340: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/hcaptha/addon/jpeglib/jdsample.o] Error 1
make: Leaving directory`/opt/test/node_modules/.0.6.10@ccap/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/test/node_modules/.0.6.10@ccap
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.0.2
npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org ccap

能帮忙看下吗，非常感谢

**Comment by DoubleSpout** [comment]
可以下载我编译好的ccap的文件在
https://github.com/DoubleSpout/ccap/tree/master/release
